[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version_provider = "commitizen"
update_changelog_on_bump = true
major_version_zero = false
changelog_file = "CHANGELOG.md"
version = "0.1.0"
changelog_incremental = true
