FROM sonar-plugin

RUN git clone https://github.com/flutter/flutter.git /usr/local/flutter

ENV PATH="/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin:${PATH}"
    
RUN flutter doctor && \
    flutter channel master && \
    flutter upgrade