---
name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    name: Continuous Integration
    uses: ./.github/workflows/ci.yaml

  is-release:
    name: Check Changes. Is Release?
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.changes.outputs.app }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0

      - id: changes
        name: Check Changes to Release
        uses: dorny/paths-filter@v2.11.0
        with:
          filters: |
            app:
              - 'bin/**'
              - 'docker/**'
              - 'scripts/build.sh'

  bump-version:
    name: Bump Version
    needs: [continuous-integration, is-release]
    if: ${{ needs.is-release.outputs.app == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.cz.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: cz
        name: Commitizen | Bump Version
        uses: commitizen-tools/commitizen-action@master
        with:
          push: true
          commit: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
